# Kubernetes
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: haskell-lang-ci-v0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: haskell-lang-ci
        version: v0
    spec:
      containers:
        - name: haskell-lang
          image: fpco/haskell-lang:ci
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "9090"
            - name: APPROOT
              value: https://ci.haskell-lang.org
          workingDir: /haskell-lang
          command:
            - haskell-lang
          ports:
            - name: http
              containerPort: 9090
      imagePullSecrets:
        - name: dockerhub-registrykey
