# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

# The different configurations we want to test. We have BUILD=cabal which uses
# cabal-install, and BUILD=stack which uses Stack. More documentation on each
# of those below.
#
# We set the compiler values here to tell Travis to use a different
# cache file per set of arguments.
#
# If you need to have different apt packages for each combination in the
# matrix, you can use a line such as:
#     addons: {apt: {packages: [libfcgi-dev,libgmp-dev]}}
matrix:
  include:

  # The Stack builds. We can pass in arbitrary Stack arguments via the ARGS
  # variable, such as using --stack-yaml to point to a different file.
  - env: BUILD=stack ARGS=""
    compiler: ": #stack default"
    addons: {apt: {packages: [libgmp-dev]}}

  # No real matrix anymore, just build stack.yaml settings on Linux

  #- env: BUILD=stack ARGS="--resolver lts-7"
  #  compiler: ": #stack GHC 8.0.1"
  #  addons: {apt: {packages: [libgmp-dev]}}

  # Nightly builds are allowed to fail
  #- env: BUILD=stack ARGS="--resolver nightly"
  #  compiler: ": #stack nightly"
  #  addons: {apt: {packages: [libgmp,libgmp-dev]}}

  # Build on OS X in addition to Linux
  #- env: BUILD=stack ARGS=""
  #  compiler: ": #stack default osx"
  #  os: osx

  #- env: BUILD=stack ARGS="--resolver lts-7"
  #  compiler: ": #stack GHC 8.0.1 OS X"
  #  os: osx

  #- env: BUILD=stack ARGS="--resolver nightly"
  #  compiler: ": #stack nightly osx"
  #  os: osx

  #allow_failures:
  #- env: BUILD=stack ARGS="--resolver nightly"
  #- env: BUILD=stack ARGS="--resolver lts-7"

before_install:
# Using compiler above sets CC to an invalid value, so unset it
- unset CC

# Download and unpack the stack executable
- export PATH=$HOME/.local/bin:$PATH
- mkdir -p ~/.local/bin
- |
  if [ `uname` = "Darwin" ]
  then
    travis_retry curl --insecure -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C ~/.local/bin

    # Install ICU libs
    brew install icu4c
    brew link icu4c --force
  else
    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  fi

install:
- echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- if [ -f configure.ac ]; then autoreconf -i; fi

# Deal with OOM situation
- stack --no-terminal --install-ghc $ARGS build haskell-src-exts
- stack --no-terminal --install-ghc $ARGS build Cabal

- stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies

script:
- stack --no-terminal $ARGS test --bench --no-run-benchmarks # Haddock is always broken --haddock --no-haddock-deps
