resolver: nightly-2018-06-20

extra-deps:
- archive: https://github.com/fpco/spiderweb/archive/7acb788f62e7c46b9d72f29331561a3d20821496.tar.gz

extra-include-dirs:
- /usr/local/opt/icu4c/include

extra-lib-dirs:
- /usr/local/opt/icu4c/lib
