- url: https://haskell-lang.org/announcements
  time: 2016-07-06T00:00:00Z
  title: New haskell-lang.org
  content: |

    *By the haskell-lang.org team: Chris Done, Chris Allen, Julie Moronuki, Michael Snoyman, Sibi Prabakaran, Gabriel Gonzalez*

    We are happy to announce the launch of a new Haskell community nexus
    site: http://haskell-lang.org/. This website is aimed at providing
    modern best practices information for the Haskell programming
    language, and in particular with providing the best possible new user
    experience. The aim is to lower the barrier to getting started with
    Haskell, and ultimately increase adoption of Haskell in the greater
    programming community.

    The launch of this website is paired with the launch of a number of
    additional community resources to aid its growth:

    * A [new Github organization](https://github.com/haskell-lang) (including [the code for the website itself](https://github.com/haskell-lang/haskell-lang))
    * A [new subreddit](https://www.reddit.com/r/haskell_lang)
    * A new `#haskell-lang` IRC channel on Freenode
    * A [new Twitter account](https://twitter.com/haskell_lang)

    These community resources are open to all to discuss the contents of
    the website, and more broadly how to make Haskell as welcoming a language, community, and
    ecosystem as can be managed. We encourage all Haskellers to join, and
    to take part in lively discussions of how to improve the state of the
    art within Haskell.

    As this community is just forming, now is the perfect time to get
    involved. Post questions and comments on Reddit, Tweet to us, send
    pull requests for the website, and open issues. This community will
    become what you put into it, so help shape it from the beginning!

    ### Why a new site?

    Since it is a common question in such statements, let us ask it
    directly here: why create a new website instead of working to
    incrementally update haskell.org? In the opinion of the team
    behind haskell-lang.org, the tooling story and general ecosystem
    infrastructure for the Haskell community has accumulated enough
    baggage that a clean break is the best use of everybody's
    time. We intend to streamline the on-boarding process for new
    developers, move away from infrastructure that is showing its
    age, and embrace newer approaches to facilitate open
    collaboration. Similar decisions have already been made in
    creating the [Stack build tool](http://haskellstack.com/) and
    [Stackage](https://www.stackage.org/).

- url: https://haskell-lang.org/announcements
  time: 2016-07-27T00:00:00Z
  title: Updates for July
  content: |
    Since July we've made a number of updates, mostly content. Here's
    a rundown:

    * Intero was added to the site under [/intero](/intero).
    * We've added Intero to the get-started page.
    * We've added the [/tutorial/](/tutorial) hierarchy, with
      [a sample tutorial](/tutorial/operators).
    * The /packages page has been renamed to
      [/libraries](/libraries). The idea being this might be more
      obvious to newcomers from other languages.
    * Added a library description for [conduit](/library/conduit).

    The complete diff can be found [here](https://github.com/haskell-lang/haskell-lang/pull/66).
